apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rbjerll1l-nodejs 
  janus-idp.io/tekton: rbjerll1l-nodejs
  backstage.io/kubernetes-id: rbjerll1l-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rbjerll1l-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml